version: '3'
services:

  nginx:
    container_name: nginx
    build: /etc/nginx
    image: docker-django/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /projects:/projects
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - django

  django:
    container_name: django
    build: /projects
    image: docker-django/django
    restart: always
    command: uwsgi --ini /projects/uwsgi.ini
    volumes:
      - /projects:/projects
      - /var/log/nginx:/var/log/nginx
